[package]
name = "minitrace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phper = "0.13.1"
anyhow = { version = "1.0.72", features = ["backtrace"] }

[lib]
crate-type = ["cdylib"]
